version: 1.0.{build}
configuration:
- Debug
- Release

before_build:
- appveyor-retry dotnet restore -v Minimal

build:
  verbosity: minimal

test:
# assemblies to test - optional
  assemblies:
    - '**\*.tests.dll'
  
test_script:
- dotnet test "test\Lodash.Net.Tests"

deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/lodash-net-tcsgl9wnwcs4/api/v2/package
    api_key:
      secure: fjt064i4jaky1o5oi4em7i5v

nuget:
  account_feed: true
  project_feed: true